In [1]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame
import sklearn
from sklearn import linear_model
from sklearn.metrics import r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold

from sklearn.linear_model import BayesianRidge, LinearRegression, ElasticNet
from sklearn.svm import SVR
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import cross_val_score

In [2]:
data = pd.read_excel('所有变量.xls')
df = DataFrame(data)
df.head

<bound method NDFrame.head of          编号   直链淀粉含量g  直链淀粉比例     重量        A1        A2        A3        A4  \
0    002N-1  3.017595  34.685   8.70  0.266629  0.273965  0.278708  0.270795   
1    003N-1  1.581878  15.585  10.15  0.524202  0.530159  0.537204  0.529693   
2    004N-1  3.149212  18.835  16.72  0.506013  0.506586  0.513458  0.500521   
3    007N-1  3.435157  32.255  10.65  0.251556  0.256260  0.263306  0.250227   
4    012N-1  2.865536  29.360   9.76  0.303613  0.310205  0.315379  0.306440   
..      ...       ...     ...    ...       ...       ...       ...       ...   
102  459N-1  2.660575  34.330   7.75  0.405291  0.398173  0.393729  0.393331   
103  466N-1  2.447317  23.330  10.49  0.387330  0.379789  0.375813  0.375563   
104  475N-1  3.901878  38.030  10.26  0.453801  0.454467  0.449704  0.449607   
105  490N-1  4.424459  35.595  12.43  0.399484  0.404151  0.398467  0.397170   
106  473N-1  5.705629  34.145  16.71  0.462239  0.466984  0.459212  0.456619   

         

In [3]:
X = df.iloc[:,3:]
y = df.iloc[:,2:3]

X_train,X_test, y_train,y_test = train_test_split(X, y, 
                                                 test_size=0.3,  # 划分比例
                                                 random_state=0)   # 随机数种子
X_train

重量        A1        A2        A3        A4        A5        A6  \
93   12.83  0.557860  0.561475  0.559576  0.550066  0.548618  0.544764   
100  10.84  0.453178  0.455545  0.450734  0.452130  0.451268  0.451164   
59   16.74  0.418308  0.421506  0.417477  0.413189  0.407511  0.403037   
27   11.49  0.438582  0.445418  0.450020  0.448650  0.445041  0.438079   
18   16.98  0.323782  0.321167  0.327093  0.323283  0.322104  0.315918   
..     ...       ...       ...       ...       ...       ...       ...   
103  10.49  0.387330  0.379789  0.375813  0.375563  0.373438  0.372258   
67    9.56  0.411056  0.400273  0.400220  0.395446  0.390958  0.386890   
64   14.02  0.441601  0.445020  0.441156  0.436489  0.434054  0.430325   
47   14.81  0.374167  0.376165  0.370528  0.365965  0.359112  0.351304   
44   11.06  0.461535  0.462439  0.459355  0.455167  0.451805  0.445407   

           A7        A8        A9  ...      A241      A242      A243  \
93   0.540008  0.535039  0.533925  ...  0.783683  0.782165  0.780460   
100  0.451589  0.449127  0.448638  ...  0.621953  0.620999  0.619460   
59   0.400292  0.395237  0.390769  ...  0.527087  0.525702  0.524879   
27   0.437260  0.432112  0.430233  ...  0.603583  0.601503  0.600342   
18   0.312552  0.303934  0.299667  ...  0.428479  0.427069  0.426271   
..        ...       ...       ...  ...       ...       ...       ...   
103  0.371867  0.366261  0.361197  ...  0.498868  0.497966  0.496522   
67   0.387437  0.380046  0.374952  ...  0.637230  0.635408  0.634473   
64   0.427985  0.424889  0.420947  ...  0.591438  0.589760  0.588684   
47   0.348808  0.341631  0.336767  ...  0.469568  0.468172  0.467459   
44   0.444150  0.440029  0.435624  ...  0.716143  0.714321  0.712914   

         A244      A245      A246      A247      A248      A249      A250  
93   0.778701  0.778228  0.776503  0.776922  0.774689  0.776035  0.777804  
100  0.617419  0.616652  0.616107  0.616266  0.615216  0.615743  0.615993  
59   0.524140  0.523727  0.523169  0.523253  0.522944  0.523510  0.523871  
27   0.598990  0.597944  0.597172  0.596634  0.596073  0.596612  0.597032  
18   0.425302  0.424520  0.423934  0.423325  0.422595  0.423442  0.424451  
..        ...       ...       ...       ...       ...       ...       ...  
103  0.494791  0.494129  0.493629  0.493963  0.492701  0.492734  0.494143  
67   0.633209  0.632432  0.631766  0.630772  0.629869  0.629767  0.630819  
64   0.587481  0.586958  0.586211  0.586017  0.585554  0.586052  0.586245  
47   0.466773  0.466495  0.465996  0.466055  0.465595  0.465925  0.466394  
44   0.711519  0.710440  0.709388  0.708849  0.707999  0.708312  0.708341  

[74 rows x 251 columns]

In [4]:
#归一化
scaler = MinMaxScaler().fit(X)
X = scaler.transform(X)

In [5]:
#降维
pca = PCA(n_components = 60)
pca.fit(X_train)
X_train = pca.transform(X_train)
X_test = pca.transform(X_test)

In [6]:
kf = KFold(n_splits=5, shuffle=True)
for train_index, test_index in kf.split(X_train):
    X_test


In [7]:
model_br = BayesianRidge()  # 建立贝叶斯回归模型

model_lr = LinearRegression() # 建立普通线性回归模型

model_etc = ElasticNet() # 建立弹性网络回归模型

model_svr = SVR() # 建立支持向量回归模型

model_gbr = GradientBoostingRegressor() # 建立梯度增强回归模型

model_names = ['BayesianRidge','LinearRegression','ElasticNet', 'SVR', 'GBR']

model_dir = [model_br, model_lr, model_etc, model_svr, model_gbr]

In [8]:
# 交叉验证评分与模型训练
n_folds = 5

cv_score_list = [] # 交叉检验结果列表

y_train_pre = [] # 各个模型预测的y值列表

y_test_pre = [] # 创建测试集预测结果列表

In [9]:
for model in model_dir:
    scores = cross_val_score(model, X_train, np.ravel(y_train), cv = n_folds, scoring = 'r2')  #对每个回归模型进行交叉验证
    cv_score_list.append(scores) # 将验证结果保存在列表中
    
    #将训练模型的预测结果保存在列表中
    y_train_pre.append(model.fit(X_train, np.ravel(y_train)).predict(X_train))
    y_test_pre.append(model.fit(X_train, np.ravel(y_train)).predict(X_test))

In [10]:
cv_score_list

[array([ 0.09174251, -0.19666195, -0.7338185 , -0.44092564, -0.1133519 ]),
 array([ -1.56755081, -61.04201322, -14.77060237,  -9.77211894,
         -7.56110411]),
 array([ 0.08834977, -0.07205663, -0.67355089, -0.41528136, -0.07308025]),
 array([-0.12465336, -0.16246272, -0.63415515, -0.2309039 , -0.31357181]),
 array([0.05621202, 0.50329314, 0.20544679, 0.01051093, 0.24300843])]